# Generated by Django 5.1.7 on 2025-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('date_time', models.CharField(help_text="e.g., 'Fri, 20:00' or 'Dec 25, 18:00'", max_length=100)),
                ('location', models.CharField(help_text='Event venue/location', max_length=255)),
                ('cover_image', models.URLField(help_text='URL to the event cover image', max_length=1000)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured events')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Promotion description')),
                ('discount_code', models.CharField(help_text='Promo code for discount', max_length=50)),
                ('tags', models.JSONField(default=list, help_text="List of tags, e.g., ['Today', 'Dine-in', '50% off']")),
                ('image', models.URLField(help_text='URL to the promotion image', max_length=1000)),
                ('valid_until', models.DateField(blank=True, help_text='Promotion expiry date', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured promotions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
