# Generated by Django 5.1.7 on 2025-09-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Brief subtitle or summary', max_length=500)),
                ('content', models.TextField(help_text='Full blog post content')),
                ('author', models.CharField(default='GoGevgelija Team', max_length=100)),
                ('category', models.CharField(choices=[('guide', 'Travel Guide'), ('food', 'Food & Dining'), ('culture', 'Culture & History'), ('events', 'Events & Activities'), ('tips', 'Travel Tips'), ('news', 'Local News'), ('lifestyle', 'Lifestyle'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', models.JSONField(default=list, help_text="List of tags, e.g., ['Travel', 'Food', 'Culture']")),
                ('cover_image', models.URLField(help_text='URL to the blog cover image', max_length=1000)),
                ('read_time_minutes', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('featured', models.BooleanField(default=False, help_text='Show in featured blogs')),
                ('published', models.BooleanField(default=True, help_text='Whether the blog is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
