# Generated by Django 5.2.6 on 2025-10-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='website_url',
            field=models.URLField(blank=True, help_text='Official website URL', max_length=500, null=True),
        ),
    ]
