# Generated by Django 5.2.6 on 2025-10-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_listing_facebook_url_listing_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_limit',
            field=models.CharField(default='All ages welcome', help_text="Age restriction (e.g., 'All ages welcome', '18+', '21+')", max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='entry_price',
            field=models.CharField(default='Free', help_text="Entry price (e.g., 'Free', '10 EUR', '500 MKD')", max_length=50),
        ),
    ]
