# Generated by Django 5.2.6 on 2025-10-04 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_age_limit_event_entry_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Ionicon name (e.g., 'musical-notes', 'restaurant', 'people')", max_length=50)),
                ('expectation', models.CharField(help_text="What to expect text (e.g., 'Live entertainment and performances')", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='core.event')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
