# Generated by Django 5.2.6 on 2025-10-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_eventexpectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expectations',
            field=models.JSONField(default=list, help_text="List of expectations with icons, e.g., [{'icon': 'musical-notes', 'text': 'Live entertainment'}, {'icon': 'restaurant', 'text': 'Food available'}]"),
        ),
        migrations.DeleteModel(
            name='EventExpectation',
        ),
    ]
