# Generated by Django 5.2.6 on 2025-10-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_event_expectations_delete_eventexpectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('culture', 'Culture'), ('food', 'Food'), ('nightlife', 'Nightlife'), ('outdoor', 'Outdoor')], default='other', max_length=20),
        ),
    ]
