# Generated by Django 5.2.6 on 2025-10-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('culture', 'Culture'), ('food', 'Food'), ('nightlife', 'Nightlife'), ('outdoor', 'Outdoor'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
