# Generated by Django 5.2.6 on 2025-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='join_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users who joined this event'),
        ),
    ]
