# Generated by Django 5.2.6 on 2025-10-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_eventjoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_code',
            field=models.CharField(blank=True, help_text='Promo code for discount (leave empty if no code required)', max_length=50),
        ),
    ]
