# Generated by Django 5.2.6 on 2025-10-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_promotion_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address', max_length=500),
        ),
        migrations.AddField(
            model_name='promotion',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL', max_length=500),
        ),
        migrations.AddField(
            model_name='promotion',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL', max_length=500),
        ),
        migrations.AddField(
            model_name='promotion',
            name='website',
            field=models.URLField(blank=True, help_text='Website URL', max_length=500),
        ),
    ]
