# Generated by Django 5.2.6 on 2025-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_promotion_address_promotion_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='has_discount_code',
            field=models.BooleanField(default=False, help_text='Whether this promotion has a discount code'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_code',
            field=models.CharField(blank=True, help_text='Promo code for discount (only used if has_discount_code is True)', max_length=50),
        ),
    ]
