# Generated by Django 5.2.6 on 2025-10-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_promotion_has_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_en',
            field=models.CharField(default='GoGevgelija Team', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_mk',
            field=models.CharField(default='GoGevgelija Team', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_en',
            field=models.TextField(help_text='Full blog post content', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_mk',
            field=models.TextField(help_text='Full blog post content', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Brief subtitle or summary', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle_mk',
            field=models.CharField(blank=True, help_text='Brief subtitle or summary', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mk',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True, help_text='Event description', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_mk',
            field=models.TextField(blank=True, help_text='Event description', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(help_text='Event venue/location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_mk',
            field=models.CharField(help_text='Event venue/location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='address_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='address_mk',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='open_time_en',
            field=models.CharField(help_text="e.g., 'Open until 23:00' or 'Mon-Fri 9:00-18:00'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='open_time_mk',
            field=models.CharField(help_text="e.g., 'Open until 23:00' or 'Mon-Fri 9:00-18:00'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_mk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='address_en',
            field=models.CharField(blank=True, help_text='Physical address', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='address_mk',
            field=models.CharField(blank=True, help_text='Physical address', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_en',
            field=models.TextField(blank=True, help_text='Promotion description', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_mk',
            field=models.TextField(blank=True, help_text='Promotion description', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_mk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
