# Generated by Django 5.2.6 on 2025-10-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='rating',
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, help_text='Listing description'),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_en',
            field=models.TextField(blank=True, help_text='Listing description', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_mk',
            field=models.TextField(blank=True, help_text='Listing description', null=True),
        ),
    ]
