# Generated by Django 5.2.6 on 2025-10-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_description_remove_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tags_mk',
            field=models.JSONField(default=list, help_text="List of tags in Macedonian, e.g., ['Скара', 'Семејно', 'Надворешно']"),
        ),
        migrations.AddField(
            model_name='listing',
            name='working_hours',
            field=models.JSONField(default=dict, help_text="Working hours structure, e.g., {'monday': '09:00-18:00', 'tuesday': '09:00-18:00', ...}"),
        ),
    ]
