# Generated by Django 5.2.6 on 2025-10-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_tags_mk_and_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='working_hours_mk',
            field=models.JSONField(default=dict, help_text="Working hours in Macedonian, e.g., {'понedelник': '09:00-18:00', 'вторник': '09:00-18:00', ...}"),
        ),
    ]
