# Generated by Django 5.2.6 on 2025-10-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_working_hours_mk'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_limit_mk',
            field=models.CharField(blank=True, help_text="Age restriction in Macedonian (e.g., 'Добредојдени се сите возрасти', '18+', '21+')", max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='entry_price_mk',
            field=models.CharField(blank=True, help_text="Entry price in Macedonian (e.g., 'Бесплатно', '10 ЕУР', '500 МКД')", max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='expectations_mk',
            field=models.JSONField(default=list, help_text="List of expectations in Macedonian with icons, e.g., [{'icon': 'musical-notes', 'text': 'Музика во живо'}, {'icon': 'restaurant', 'text': 'Достапна храна'}]"),
        ),
    ]
