# Generated by Django 5.2.6 on 2025-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_event_mk_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='tags_mk',
            field=models.JSONField(default=list, help_text="List of tags in Macedonian, e.g., ['Денес', 'За јадење', '50% попуст']"),
        ),
    ]
