# Generated by Django 5.2.6 on 2025-10-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_promotion_tags_mk'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
    ]
