# Generated by Django 5.1.7 on 2025-10-08 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_step1_add_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional category image URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select category from available categories', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
    ]
