# Generated by Django 5.1.7 on 2025-10-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_event_category_step1'),
    ]

    operations = [
        # Step 4: Remove old category field
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        
        # Step 5: Rename category_new to category
        migrations.RenameField(
            model_name='event',
            old_name='category_new',
            new_name='category',
        ),
    ]